### ISSUE TITLE
Scroll problem

### ISSUE THREAD

**Issue by ghost** [damienpontifex/BlogCodeSamples#1]
If you keep on writing until the textview gets close to keyboard or bottom margin, the table view starts scrolling up and down

**Comment by damienpontifex** [comment]
I have been trying to figure out a solution. Haven't found one yet and have submitted a technical support request to Apple this morning. I'll try and update as soon as possible.

**Comment by ItsTipTop** [comment]
Same problem. Wait for your solution)

**Comment by ItsTipTop** [comment]
I do not know how but adding footer view fix this bug:
<code>self.tableView.tableFooterView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, self.tableView.frameWidth, 200)];</code>

**Comment by swaterfall** [comment]
Adding a footer view did nothing for me. 

@damienpontifex any word back from Apple?

**Comment by damienpontifex** [comment]
Technical support came to the same conclusion as we have. As was their suggestion as a result, I have submitted a bug report and also passed that to technical support.

**Comment by swaterfall** [comment]
ah great, hopefully they will fix it soon!

**Comment by joshdance** [comment]
I also submitted a bug report to Apple. Here is the radar number: 20105573. I also posted it on Open Radar http://openradar.appspot.com/radar?id=6381017677955072

If you have the bug, submit a Radar and reference mine, as dups increase priority.

**Comment by 5amfung** [comment]
I have been looking for a working solution like this for more than 6 months.  Too bad that there's a jump issue that makes it somewhat unbearable.

I noticed that after having typing about 10+ lines with jumps, if you scroll to the bottom (assuming you were editing the last row) and continue to type, it doesn't jump anymore.  The behavior is strange.

**Comment by nabinchha** [comment]
We made it sort of usable by getting the table view to only update cells (beginUpdates/endUpdates) when a new line is detected (https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSString_AppKitAdditions/index.html#//apple_ref/occ/instm/NSString/boundingRectWithSize:options:attributes:).

It doesn't solve the problem entirely, but it does make it bearable. Hope it is helpful to others.

**Comment by swaterfall** [comment]
@nabinchha Just tried that and it does seem to help, what did you do to make the CGSize width exactly match the text views text width? My calculation doesn't seem to match the actual width so it updates a few characters into the next line.

**Comment by joshdance** [comment]
@swaterfall We were able to make it update only on new lines which helped the problem greatly. What are you using to calculate? 

Here is what we did. 

```
    func TextCellTextViewDidChange(controller: TextCell, withTextView textView: UITextView)
    {
        let size: CGSize    = controller.myTextView.frame.size
        let newSize: CGSize = controller.myTextView.sizeThatFits(CGSizeMake(size.width, CGFloat(FLT_MAX)))

        // Resize cell only when cell's size is changes
        if size.height != newSize.height
        {
            controller.myTextView.frame.size = newSize
            self.tableView.beginUpdates()
            /*
            if self.isIphone4sOr5 == true {
                self.tableView.estimatedRowHeight = controller.frame.height + 44
            } else {
                self.tableView.estimatedRowHeight = controller.frame.height + 50
            }
            */
            self.tableView.endUpdates()
        }
        self.setDirty()
    }
```

**Comment by 5amfung** [comment]
@joshdance, your solution works very well for my case.  Thank you so much for providing the snippet.

**Comment by ItsTipTop** [comment]
@joshdance when size of the textview changes table scrolls too. But i fixed it

<code>

```
CGSize size  = textView.frame.size;
CGSize newSize = [textView sizeThatFits:CGSizeMake(size.width, 99999)];

// Resize cell only when cell's size is changes
if (size.height != newSize.height)
{
    [UIView setAnimationsEnabled:NO];
    [self.tableView beginUpdates];
    [self.tableView endUpdates];
    [UIView setAnimationsEnabled:YES];
    [self.tableView scrollToRowAtIndexPath:[NSIndexPath indexPathForRow:2 inSection:0] atScrollPosition:UITableViewScrollPositionBottom animated:NO]; // indexPath for textview cell
}
```

</code>

Thank you so much for providing the snippet.

**Comment by joshdance** [comment]
Tried your code, but couldn't get it to work. My tableview still jumps when
the textview changes. Could you post screencast of how yours works?

On Wed, Mar 25, 2015 at 6:41 PM, Oleg notifications@github.com wrote:

> UIView

## 

-J

---

Joshua Dance | Problem Solver | 425-301-9137 | [image: Twitter]
http://www.twitter.com/joshdance [image: YouTube]
http://www.youtube.com/joshuajaydan
joshdance.me/
helpcapeverde.org/

**Comment by ItsTipTop** [comment]
@joshdance of course
first - mine. 
Just turn off tableview updates animation 
<code>[UIView setAnimationsEnabled:NO];</code>
and scroll to bottom textview cell 
![1](https://cloud.githubusercontent.com/assets/1473763/6846676/176a0ed0-d3d1-11e4-8791-56dfde80400d.gif)

second - yours
![2](https://cloud.githubusercontent.com/assets/1473763/6846758/df339e4a-d3d1-11e4-9900-44b35be82da5.gif)

**Comment by damienpontifex** [comment]
Thanks @ItsTipTop and @joshdance I combined your suggestions and integrated into the MultiLineTextInputTableViewCell class with commit 44da251 on the branch 'scroll-problem'

I have run this on the simulator and on my phone and this seems to work. Can others test this fix from that branch and see if it solves all our issues?

**Comment by ItsTipTop** [comment]
@damienpontifex thank you for your work)

**Comment by damienpontifex** [comment]
@ItsTipTop did you have a run with that latest commit/branch? Come across any issues?

**Comment by ItsTipTop** [comment]
@damienpontifex in my case i do not use your library but same algorithm. After disabling animations and scrolling to bottom of the cell it works fine

**Comment by nabinchha** [comment]
@ItsTipTop thanks for your snippet. Disabling UIView animation before beginUpdates and reenabling it after endUpdates was just what we needed!

**Comment by damienpontifex** [comment]
Awesome. Thanks everyone :) 

Collaboration for the win. This would've taken me many, many hours to work out a solution on my own.

**Comment by nabinchha** [comment]
@swaterfall I had the same issue until I tried to fit text in a rect slightly smaller than the textview itself. I think the solution provided by @joshdance works better.

**Comment by archerrito** [comment]
One issue I am having is multiple TextViews resizing a single cell.  Any suggestions as to how to solve this issue?

**Comment by joshdance** [comment]
You are editing multiple textviews at once? Or you have multiple textviews
in your cell? Code sample and video example of problem?

On Tue, Apr 28, 2015 at 2:17 PM, Archer notifications@github.com wrote:

> One issue I am having is multiple TextViews resizing a single cell. Any
> suggestions as to how to solve this issue?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/damienpontifex/BlogCodeSamples/issues/1#issuecomment-97195266
> .

## 

-J

---

Joshua Dance | Problem Solver | 425-301-9137 | [image: Twitter]
http://www.twitter.com/joshdance [image: YouTube]
http://www.youtube.com/joshuajaydan
joshdance.me/
helpcapeverde.org/

**Comment by archerrito** [comment]
I have multiple textviews in one cell, stacked vertically.  The problem is that if I go to a second line on any of them it jumps up and I can no longer edit the TextView in view.
![screen shot 2015-04-28 at 3 23 15 pm](https://cloud.githubusercontent.com/assets/3663539/7379446/a31341ec-edba-11e4-9c83-41b21f80e58f.png)

Then if we go to a new line, the keyboard jumps up and doesnt allow editing on the lower views
![screen shot 2015-04-28 at 3 33 12 pm](https://cloud.githubusercontent.com/assets/3663539/7379649/ff724e78-edbb-11e4-9f33-4527e5db9973.png)

**Comment by joshdance** [comment]
Hmm. Post a video (you can record with Quicktime -
http://digitalwriting101.net/content/how-to-make-a-screencast-with-quicktime-x-for-mac/)
and your code sample. Right now I don't know why it is doing that.

Joshua

On Tue, Apr 28, 2015 at 2:34 PM, Archer notifications@github.com wrote:

> I have multiple textviews in one cell, stacked vertically. The problem is
> that if I go to a second line on any of them it jumps up and I can no
> longer edit the TextView in view.
> [image: screen shot 2015-04-28 at 3 23 15 pm]
> https://cloud.githubusercontent.com/assets/3663539/7379446/a31341ec-edba-11e4-9c83-41b21f80e58f.png
> 
> Then if we go to a new line, the keyboard jumps up and doesnt allow
> editing on the lower views
> [image: screen shot 2015-04-28 at 3 33 12 pm]
> https://cloud.githubusercontent.com/assets/3663539/7379649/ff724e78-edbb-11e4-9f33-4527e5db9973.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/damienpontifex/BlogCodeSamples/issues/1#issuecomment-97199709
> .

## 

-J

---

Joshua Dance | Problem Solver | 425-301-9137 | [image: Twitter]
http://www.twitter.com/joshdance [image: YouTube]
http://www.youtube.com/joshuajaydan
joshdance.me/
helpcapeverde.org/

**Comment by archerrito** [comment]
Hey Josh, its a client app, not allowed to reveal that much through video.  Sorry, wish I could as it would only help myself. Essentially we have textview, two labels, then three more textviews stacked vertically.  The labels are static, the textviews resize.  What happens is that when the bottom three textviews are pushed offscreen and we try to add characters to say a bottom textview, then each inputted character it trys to rescroll up to the top, essentially making jump back and forth between where you add the character and where it wants to rescroll to the top.

**Comment by ErickB14** [comment]
When i implemnet this cell with other custom cells .... I have a problem ..when i scroll to up... 
Here is all very well..
![001](https://cloud.githubusercontent.com/assets/7366796/10054380/56679e0a-61f6-11e5-8462-d0806e311051.jpg)

When i scrolling to up ...
![002](https://cloud.githubusercontent.com/assets/7366796/10054399/71f9ee0c-61f6-11e5-955d-220985de9cd8.jpg)

When finish the scroll to up.. apparently okay, but in the log i find some warnings

![003](https://cloud.githubusercontent.com/assets/7366796/10054428/9d0880c2-61f6-11e5-8e1a-b4ab7eebf02d.jpg)

![005](https://cloud.githubusercontent.com/assets/7366796/10054493/e8546f1e-61f6-11e5-9adf-f4d66d37d5c4.jpg)

And.. when i write in the cell 

![004](https://cloud.githubusercontent.com/assets/7366796/10054501/f7ca6e4e-61f6-11e5-90ab-f5fc1f80c2bf.jpg)

I dont know why do this, if i have two cell, one of each (Multiline....Cell and my Custom Cell)?

**Comment by mutech** [comment]
Thanks for your work guys. Helps me!

EDIT: for the case of insertion in the middle of text I found something for iOS7+, here is my solution:

```
- (void)textViewDidChange:(UITextView *)textView
{
    CGSize size = textView.frame.size;
    CGSize newSize = [textView sizeThatFits:CGSizeMake(size.width, FLT_MAX)];
    if (size.height != newSize.height)
    {
        BOOL wasAnimating = [UIView areAnimationsEnabled];
        [UIView setAnimationsEnabled:NO];
        [self.tableView beginUpdates];
        [self.tableView endUpdates];
        [UIView setAnimationsEnabled:wasAnimating];
    }

    UITableViewCell* cell = (UITableViewCell*)[textView superviewOfType:[UITableViewCell class]];
    CGPoint position = cell.frame.origin;
    CGRect cursorR = [textView caretRectForPosition:textView.selectedTextRange.end];
    CGRect scrollR = CGRectMake(cursorR.origin.x + position.x,
                                cursorR.origin.y + position.y,
                                cursorR.size.width, cursorR.size.height);
    [self.tableView scrollRectToVisible:scrollR animated:YES];
}
```

EDIT: PS: superviewOfType is a category doing what it says

**Comment by damienpontifex** [comment]
@mutech scrolling to the the caret position probably makes sense. I haven't tested it yet, but maybe also a check to not scroll if the rect is already visible?

I may pull it up again this week and update and test. Thanks for your thoughts and input

**Comment by mutech** [comment]
No need to check, since the TV won't scroll if the rect is already fully visible
