### ISSUE TITLE
MultiLineTextInputTableViewCell doesn't work with static cells, dynamic only

### ISSUE THREAD

**Issue by ghost** [damienpontifex/BlogCodeSamples#4]
Strangely, if one changes the table in the SelfSizingTextViewTableCell project to use static cells instead of dynamic, the auto-resizing cell machinery does not work and instead the rows heights from the storyboard are used. I thought this wasn't the case with Xcode 6.4 / iOS 8, but I tried this in both Xcode 7/iOS 9 and Xcode 7.1/iOS 9.1.

**Comment by ghost** [comment]
Interesting, according to the comment from snapper303 on August 25, 2015, 8:28 PM (sadly no direct link or anchor) on http://www.raywenderlich.com/87975/dynamic-table-view-cell-height-ios-8-swift, 

> In order for it to work in iOS 9, I had to delete those methods and use the delegate methods as follows:
> 
> ``` objective-c
> - (CGFloat)tableView:(UITableView *)tableView estimatedHeightForRowAtIndexPath:(NSIndexPath *)indexPath {
>     return 150;
> }
> - (CGFloat) tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath {
>     return UITableViewAutomaticDimension;
> }
> ```

and sure enough, if I override those two methods, `MultiLineTextInputTableViewCell` works with static cells on iOS 9!

**Comment by damienpontifex** [comment]
@pizthewiz thanks for that. Changed my code as does't make any difference for the dynamic cell case, but great that this fixes the issue for static cells

**Comment by ghost** [comment]
Glad to help and thanks for the examples to begin with! I filed a radar too as it seems like a regression from iOS 8 behavior without any mention in the docs / headers to indicate it was purposeful rdar://problem/23310774 UITableView estimatedRowHeight property doesn't work with static cells, iOS 9 regression
